### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by telagabirudigital** [MusheAbdulHakim/Laravel-Smarthr#31] opened 2024-08-19 09:47 UTC
i cant use this system because load so long on development
![Uploading Screenshot 2024-08-19 at 17.46.08.png…]()

**Comment by MusheAbdulHakim** [comment] 2024-08-21 18:07
I am closing this issue since it's not a bug. 
Reference [Discussion](https://github.com/MusheAbdulHakim/Laravel-Smarthr/discussions/32)

**Closed by MusheAbdulHakim** 2024-08-21 18:07 UTC
